language: python
python:
  - "2.7"
  - "3.6"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install httmock
# command to run tests
script: nosetests -v --with-coverage --cover-package=xunleipy

after_success:
  - pip install coveralls
  - coveralls
